-- This script creates all tables for the Digital Warranty Tracker (Warracker) application.
-- It keeps the original users, warranties, and notifications tables and adds the new requested tables.

-- Drop tables in reverse order of dependency to avoid errors
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW v_warranty_status';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE service_claims';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE notifications';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE warranties';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE products';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE admin';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/


-- =================================================================
-- CORE TABLES (As requested, these are unchanged)
-- =================================================================

-- 1. USERS TABLE: Stores regular customer login information
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(200) NOT NULL
);

-- 2. WARRANTIES TABLE: Stores product warranty details for each user
CREATE TABLE warranties (
    warranty_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    product_name VARCHAR2(100) NOT NULL,
    brand VARCHAR2(100),
    product_id NUMBER, -- optional FK link to products (auto-added from warranties)
    purchase_date DATE NOT NULL,
    warranty_period_months NUMBER NOT NULL,
    expiry_date DATE NOT NULL,
    invoice_path VARCHAR2(255),
    CONSTRAINT fk_user_warranties
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- 3. NOTIFICATIONS TABLE: Stores alerts for users
CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    warranty_id NUMBER, -- Link to the specific warranty
    message VARCHAR2(300) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Unread' CHECK(status IN ('Unread', 'Read')),
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_notification_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);


-- =================================================================
-- NEW TABLES (Added as requested)
-- =================================================================

-- 4. ADMIN TABLE: Stores administrator login information
CREATE TABLE admin (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    created_at DATE DEFAULT SYSDATE
);

-- 5. PRODUCTS TABLE: A master list of products that admins can manage
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR2(100) NOT NULL,
    model_name VARCHAR2(150) NOT NULL,
    category VARCHAR2(100), -- e.g., 'Electronics', 'Appliance'
    image_url VARCHAR2(255),  -- Optional path to a generic product image
    verified CHAR(1) DEFAULT 'N' CHECK (verified IN ('Y','N')),
    added_by NUMBER NULL, -- user who triggered auto-add
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_products_added_by_user FOREIGN KEY (added_by) REFERENCES users(user_id)
);

-- Warranties -> Products foreign key
ALTER TABLE warranties
  ADD CONSTRAINT fk_warranty_product
  FOREIGN KEY (product_id)
  REFERENCES products(product_id);

-- Normalized uniqueness on products to avoid duplicates by brand/model (case/space-insensitive)
CREATE UNIQUE INDEX ux_products_brand_model_norm
  ON products (LOWER(TRIM(brand)), LOWER(TRIM(model_name)));

-- 6. SERVICE_CLAIMS TABLE: Tracks service/claim requests for a specific warranty
CREATE TABLE service_claims (
    claim_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warranty_id NUMBER NOT NULL, -- Links directly to the user's warranty
    claim_date DATE DEFAULT SYSDATE NOT NULL,
    description VARCHAR2(1000) NOT NULL,
    status VARCHAR2(50) DEFAULT 'Pending' NOT NULL CHECK(status IN ('Pending', 'In Progress', 'Completed', 'Denied')),
    service_center VARCHAR2(200),
    service_notes CLOB, -- For admins to add detailed updates
    
    CONSTRAINT fk_claim_warranty
        FOREIGN KEY (warranty_id)
        REFERENCES warranties(warranty_id)
        ON DELETE CASCADE -- If a warranty is deleted, its claims are also deleted
);

CREATE OR REPLACE VIEW v_warranty_status AS
SELECT w.warranty_id AS warranty_id,
       w.product_name AS product_name,
       u.full_name AS user_name,
       w.purchase_date,
       w.warranty_period_months,
       CASE 
           WHEN ADD_MONTHS(w.purchase_date, w.warranty_period_months) >= SYSDATE THEN 'Active'
           ELSE 'Expired'
       END AS warranty_status
FROM warranties w
JOIN users u ON w.user_id = u.user_id;

-- Commit all table creations to the database
COMMIT;
